settings:
  title: '异构云平台 - 状态页'
  url: 'http://monitor.yimoex.cn/'
  logo: logo.jpg # image in ./public/
  daysInHistogram: 80
  collectResponseTimes: true

  allmonitorsOperational: '系统正常运行中!'
  notAllmonitorsOperational: '系统未完全运行!'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 事件'

monitors:
  - id: api
    name: 异构云 - API站
    description: '个人应用网站.'
    url: 'https://api.yimoex.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: mc
    name: Minecraft异响云官网
    url: 'https://mc.yimoex.cn'
    method: GET
    expectStatus: 200

  - id: ai
    name: 异心云AI聚合平台
    url: 'https://ai.yimoex.cn'
    method: GET
    expectStatus: 200

  - id: pro
    name: 异心云AI聚合平台 (Pro线路)
    url: 'https://pro.yimoex.cn'
    method: GET
    expectStatus: 200

  - id: reader
    name: Koodo Reader
    url: 'https://reader.yimoex.cn'
    method: GET
    expectStatus: 200

  - id: blog
    name: 个人博客(由Xlog强力驱动)
    url: 'https://blog.yimoex.cn'
    method: GET
    expectStatus: 200

