settings:
  title: '异构云平台 - 状态页'
  url: 'http://monitor.yimoex.cn/' # used for Slack messages
  logo: logo.jpg # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '系统正常运行中!'
  notAllmonitorsOperational: '系统未完全运行!'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切很好'
  dayInHistogramNotOperational: ' 事件'

monitors:
  - id: api
    name: API站
    description: '个人应用网站.'
    url: 'https://api.yimoex.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: mc
    name: Minecraft异响云官网
    url: 'https://mc.yimoex.cn'
    method: GET
    expectStatus: 200

  - id: blog
    name: 个人博客(由Xlog强力驱动)
    url: 'https://blog.yimoidc.cn'
    method: GET
    expectStatus: 200
